### ISSUE TITLE
fix ERROR 1: follow modal error

### ISSUE THREAD

**Issue by ChanReMin** [ducchung0002/PBL6#34]
FIX:
Khi số lượng follower hoặc following của tài khoản đang đăng nhập = 0 thì mỗi lần click sẽ tạo ra bản mới và không xóa đi bản cũ. Khi f5 thì mới mất đi

**Comment by ducchung0002** [comment]
fix in [pull#35](https://github.com/ducchung0002/PBL6/pull/35)
